### PR TITLE
UPDATEBROKERAGECONTRACT Nan % bugfix.

### PR DESCRIPTION
**Pull request by RyoungHo**
set brokerage 0 => contract['brokerage'] is null.
100 - contract['brokerage'] => Nan.

### CODE REVIEW

**Comment by RyoungHo** [comment]
https://tronscan.org/#/transaction/90546e92828a0cc350d3436d72147d3cc4496b59443ab30a05253a0e5bd1e241

NaN % Link.

**Comment by RyoungHo** [comment]
https://tronscan.org/#/sr/votes

Currently Skypeople Voter Reward rate 100 %
But, Render 0 %

fix bug.

**Comment by myfocus** [comment]
We have fixed this issue in the latest version, thank you for your help.

**Comment by myfocus** [comment]
If you want  the voter reward to be 100%,  you should set brokerage  as 0

**Comment by RyoungHo** [comment]
@myfocus yeah. set brokerage 0. thanks :)

**Pull request closed without merging**
